### ISSUE TITLE
build: libreadline-dev needed

### ISSUE THREAD

**Issue by trombonekenny** [mdwheele/classroom-docker#1]
To get Step 15/20 "RUN rbenv install 2.4.2" to work, I had to add `libreadline-dev` to the `Dockerfile` apt-get install.

**Comment by mdwheele** [comment]
Yeah, I was using a different base image (`ruby:2.4.2`) haha. That was part of what I wanted to fix up this morning. Does it complete after that package add? I wouldn't be surprised if there are other missing issues. If it gives you any more problems, I'll switch back to `ruby:2.4.2`.

**Comment by trombonekenny** [comment]
```
Step 19/20 : RUN gem install bundler && rbenv rehash
 ---> Running in 085a94d342da
/bin/sh: 1: gem: not found
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c gem install bundler && rbenv rehash' returned a non-zero code: 127
```

**Comment by mdwheele** [comment]
Yeahhhhh, lemme roll that back to ruby:2.4.2. It was working without all the shenanigans on that image. I was just trying to cut 20MB off (or whatever it was)... that's what I get.

**Comment by trombonekenny** [comment]
Optimizing docker layers is an art.... a dark art.

**Comment by mdwheele** [comment]
Just reverted that on `master`. I'm building it on the side while waiting on OpenShift to ... shift openly.

**Comment by trombonekenny** [comment]
It feels like if you're running in a ruby container, running "RUN rbenv install 2.4.2" shouldn't be needed, right?

**Comment by mdwheele** [comment]
I thought that. Then I tried running classroom and got all manner of weird pathing issues with bundler. When I used rbenv, everything magically worked. It's 100% the same binary either way.

I think I'm going to work this back towards a slimmer base image and work out kinks, but this seems to work for quick development. I'll likely either use this project to run our production instance (when enterprise support is merged) so I do want to get it towards "more professional". Part of that will be dropping the "--network=host" stuff. All that needs to be exposed is 443:5000 -> workspace.

**Comment by mdwheele** [comment]
Alright, I was able to build the image and got a shell. 

Ran `script/setup` and got:

```
===> Setting up DB...
Ignoring bindex-0.5.0 because its extensions are not built.  Try: gem pristine bindex --version 0.5.0
Ignoring bootsnap-1.1.2 because its extensions are not built.  Try: gem pristine bootsnap --version 1.1.2
Could not find nokogiri-1.8.0 in any of the sources
```

This is "typical GitHub Classroom shenanigans". I typically run `script/setup` again and all is well. Probably should open an issue upstream.

**Comment by mdwheele** [comment]
In case you didn't run into this yet, you also have to modify `config/database.yml` to set `host` to `localhost` for postgresql to work correctly:

```
mdwheele@blaze:~/classroom/.docker$ cat ../config/database.yml 
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5

development:
  <<: *default
  database: classroom_development

test:
  <<: *default
  database: classroom_test
```

I just ignore changes to that file locally for development (another thing I should send a PR for):

```
git update-index --assume-unchanged config/database.yml
```
